monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 30 # How many messages should be saved? Prevent memory leaks
        business_event_handler_buffer:
            level: error
        nested:
            type: stream
            path:  "php://stdout"
            level: error
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
